### ISSUE TITLE
What port do I attach to?

### ISSUE THREAD

**Issue by MotchHmmF** [henkelmax/simple-voice-chat#170]
Hello,
I'm currently hosting a Fabric server on my home device that I am attempting to add the Voice Chat to.
I have port forwarded for 24454 and when I launch the server the only log of the mod is this:
[21:44:11] [VoiceChatServerThread/INFO]: Server started at port 24454
Link to image of ports forwarded: ![Port Forward](https://user-images.githubusercontent.com/83347365/116401875-17db0d00-a86f-11eb-90a1-16debfc6db66.PNG)

The voicechat-sever.properties file looks as follows:
port=24454
bind_address=0.0.0.0
voice_fade_distance=16.0
voice_distance=32.0
codec=VOIP
keep_alive=1000
mtu_size=1024

I am running Fabric 0.11.3
With mods:
Fabric-api-0.32.5+1.16
voicechat-1.16.5-1.1.6

None of the tinkering I have done has worked and I'm unsure what to try next
If there is also another person with similar issues that I missed I am sorry for asking a question already asked in the past
I looked at the links commented on #160 and cant find an answer

Any help would be much appreciated, Thanks in advance

Links to txt versions of
Mod properties: [voicechat-serverproperties.txt](https://github.com/henkelmax/simple-voice-chat/files/6391635/voicechat-serverproperties.txt)
Server Properties: [serverproperties.txt](https://github.com/henkelmax/simple-voice-chat/files/6391621/serverproperties.txt)
My latest Log: [latest.log](https://github.com/henkelmax/simple-voice-chat/files/6391628/latest.log)

When I set bound IP to my servers IP:
[22:06:25] [VoiceChatServerThread/ERROR]: Failed to bind to address '110.22.121.5'
[22:06:25] [VoiceChatServerThread/INFO]: [STDERR]: java.net.BindException: Cannot assign requested address: Cannot bind
[22:06:25] [Query Listener #1/INFO]: Query running on (My IPv4:25565
[22:06:25] [VoiceChatServerThread/INFO]: [STDERR]: 	at java.net.DualStackPlainDatagramSocketImpl.socketBind(Native Method)
[22:06:25] [VoiceChatServerThread/INFO]: [STDERR]: 	at java.net.DualStackPlainDatagramSocketImpl.bind0(Unknown Source)
[22:06:25] [VoiceChatServerThread/INFO]: [STDERR]: 	at java.net.AbstractPlainDatagramSocketImpl.bind(Unknown Source)
[22:06:25] [VoiceChatServerThread/INFO]: [STDERR]: 	at java.net.DatagramSocket.bind(Unknown Source)
[22:06:26] [VoiceChatServerThread/INFO]: [STDERR]: 	at java.net.DatagramSocket.<init>(Unknown Source)
[22:06:26] [VoiceChatServerThread/INFO]: [STDERR]: 	at java.net.DatagramSocket.<init>(Unknown Source)
[22:06:26] [VoiceChatServerThread/INFO]: [STDERR]: 	at de.maxhenkel.voicechat.voice.server.Server.run(Server.java:62)"

When I set bound IP to my IPv4 There are no errors but it doesn't connect

When I set bound IP to my IPv6 (Don't know why I tried this)
It breaks up my bind address with /'s and then does the same as if its set to 0.0.0.0 of saying its running on the port then doing nothing

**Comment by henkelmax** [comment]
You only need to bind to an IP address if you have multiple adapters. If you forwarded your port properly, it will work without this.
