### ISSUE TITLE
Kicked from server when logged in

### ISSUE THREAD

**Issue by joex92** [henkelmax/simple-voice-chat#270]
**Bug description**
The server kicked me out even when having the mod version on client on login.

**Steps to reproduce the issue**
just add it to a 1.17.1 paper fork server

**Expected behavior**
being able to use the mod with the server

<details>
<summary>Logs</summary>

Without mod on client
```yaml
[23:51:11] [User Authenticator #1/INFO]: UUID of player joex92 is e4362f3a-c8a7-3d76-8d93-9ac2953b6cdf
[23:51:12] [Server thread/INFO]: joex92 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: Badly compressed packet - size of 2 is below server threshold of 256
[23:51:29] [User Authenticator #1/INFO]: UUID of player joex92 is e4362f3a-c8a7-3d76-8d93-9ac2953b6cdf
[23:51:30] [Server thread/ERROR]: [NexEngine] Could not add packet listener for joex92 !
[23:51:30] [Server thread/WARN]: java.util.NoSuchElementException: packet_handler
[23:51:30] [Server thread/WARN]: 	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073)
[23:51:30] [Server thread/WARN]: 	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248)
[23:51:30] [Server thread/WARN]: 	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237)
[23:51:30] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:61)
[23:51:30] [Server thread/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:313)
[23:51:30] [Server thread/WARN]: 	at NexEngine.jar//su.nexmedia.engine.nms.packets.PacketManager.injectPlayer(PacketManager.java:117)
[23:51:30] [Server thread/WARN]: 	at NexEngine.jar//su.nexmedia.engine.nms.packets.PacketManager.onJoin(PacketManager.java:127)
[23:51:30] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor117.execute(Unknown Source)
[23:51:30] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[23:51:30] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[23:51:30] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[23:51:30] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[23:51:30] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:360)
[23:51:30] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:302)
[23:51:30] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.tick(PlayerConnection.java:307)
[23:51:30] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:555)
[23:51:30] [Server thread/WARN]: 	at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:201)
[23:51:30] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1643)
[23:51:30] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[23:51:30] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1465)
[23:51:30] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1261)
[23:51:30] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[23:51:30] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[23:51:31] [Server thread/WARN]: [ClientDetector] Loaded class org.geysermc.connector.GeyserConnector from Geyser-Spigot v1.4.1-SNAPSHOT which is not a depend, softdepend or loadbefore of this plugin.
[23:51:31] [Server thread/INFO]: [BlueMapOfflineSkinSupport] joex92 joined the server! Calling writeTrueCompositedPlayerHeadForBukkitPlayerAsynchronousCallback()...
[23:51:31] [Server thread/INFO]: joex92 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: Badly compressed packet - size of 2 is below server threshold of 256
```
with mod on client
```yaml
[01:38:05] [LoginProcessingThread/INFO]: UUID of player joex92 is e4362f3a-c8a7-3d76-8d93-9ac2953b6cdf
[01:38:05] [Netty Server IO #0/WARN]: [io.netty.util.concurrent.DefaultPromise] An exception was thrown by protocolsupport.zplatform.impl.spigot.network.SpigotNetworkManagerWrapper$$Lambda$10940/0x00000008032346b8.operationComplete()
java.lang.NoSuchMethodError: 'void net.minecraft.network.PacketDecompressor.<init>(int, boolean)'
	at protocolsupport.zplatform.impl.spigot.network.pipeline.SpigotPacketDecompressor.<init>(SpigotPacketDecompressor.java:22) ~[ProtocolSupport.jar:?]
	at protocolsupport.zplatform.impl.spigot.SpigotMiscUtils.enableCompression(SpigotMiscUtils.java:339) ~[ProtocolSupport.jar:?]
	at protocolsupport.protocol.packet.handler.AbstractLoginListener.lambda$finishLogin$11(AbstractLoginListener.java:271) ~[ProtocolSupport.jar:?]
	at protocolsupport.zplatform.impl.spigot.network.SpigotNetworkManagerWrapper.lambda$sendPacketBlocking$2(SpigotNetworkManagerWrapper.java:119) ~[ProtocolSupport.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at net.minecraft.network.NetworkManager.a(NetworkManager.java:453) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at net.minecraft.network.NetworkManager.lambda$writePacket$8(NetworkManager.java:424) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351) ~[ProtocolLib.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at java.lang.Thread.run(Unknown Source) [?:?]
[01:38:05] [Server thread/INFO]: joex92 lost connection: Disconnected
[01:38:27] [LoginProcessingThread/INFO]: UUID of player joex92 is e4362f3a-c8a7-3d76-8d93-9ac2953b6cdf
[01:38:27] [Netty Server IO #2/WARN]: [io.netty.util.concurrent.DefaultPromise] An exception was thrown by protocolsupport.zplatform.impl.spigot.network.SpigotNetworkManagerWrapper$$Lambda$10940/0x00000008032346b8.operationComplete()
java.lang.NoSuchMethodError: 'void net.minecraft.network.PacketDecompressor.<init>(int, boolean)'
	at protocolsupport.zplatform.impl.spigot.network.pipeline.SpigotPacketDecompressor.<init>(SpigotPacketDecompressor.java:22) ~[ProtocolSupport.jar:?]
	at protocolsupport.zplatform.impl.spigot.SpigotMiscUtils.enableCompression(SpigotMiscUtils.java:339) ~[ProtocolSupport.jar:?]
	at protocolsupport.protocol.packet.handler.AbstractLoginListener.lambda$finishLogin$11(AbstractLoginListener.java:271) ~[ProtocolSupport.jar:?]
	at protocolsupport.zplatform.impl.spigot.network.SpigotNetworkManagerWrapper.lambda$sendPacketBlocking$2(SpigotNetworkManagerWrapper.java:119) ~[ProtocolSupport.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at net.minecraft.network.NetworkManager.a(NetworkManager.java:453) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at net.minecraft.network.NetworkManager.lambda$writePacket$8(NetworkManager.java:424) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351) ~[ProtocolLib.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
	at java.lang.Thread.run(Unknown Source) [?:?]
[01:38:27] [Server thread/INFO]: joex92 lost connection: Disconnected
```
</details>

**Versions**
- Minecraft version latest Paper fork Tuinity 1.17.1
- Forge/Fabric version latest
- Mod version latest (downloaded it Aug 18th 2021)

**Other mods (client-side)**
![image](https://user-images.githubusercontent.com/645579/130176882-20e26400-4c95-4430-b16f-6e93b1f5544d.png)

**Comment by henkelmax** [comment]
Please send me the full logs of the client and server.
Please also update protocollib.
Please also test if this happens with vanilla Paper, since we don't support Tuinity.

**Comment by joex92** [comment]
> Please send me the full logs of the client and server.

Server Logs
[Without the voicechat mod client-side](https://github.com/henkelmax/simple-voice-chat/files/7024323/2021-08-17-3.log)
[With the voicechat mod client-side](https://github.com/henkelmax/simple-voice-chat/files/7024327/2021-08-18-2.log)
Client Logs
[Without the voicechat mod at timestamp at line 57302](https://github.com/henkelmax/simple-voice-chat/files/7024399/2021-08-16-1.log)
[With the voicechat mod at timestamp 01:38:06](https://github.com/henkelmax/simple-voice-chat/files/7024343/2021-08-18-2.log)

> Please also update protocollib.

Always has been updated

> Please also test if this happens with vanilla Paper, since we don't support Tuinity.

ok, I'll test it out, although Tuinity is a paper fork and should be the same... 
Also I remembered that I used the public IP (which only has the mc port open) instead of the local IP, so yeah, I'm going to test that again...

**Comment by henkelmax** [comment]
This is not a voice chat issue. It seems that protocollib is not compatible with your server or something.

> ok, I'll test it out, although Tuinity is a paper fork and should be the same...

If it would be the same, there would be no reason to use it.

**Comment by joex92** [comment]
> This is not a voice chat issue. It seems that protocollib is not compatible with your server or something.

ok, I just rechecked everything and redownloaded the proper plugins again and it worked fine, no errors with or without the mod client-side, with Tuinity... so maybe the issue was with 1 of the 2 plugins i was testing at the same time with VoiceChat... anyways thanks...
 
> > ok, I'll test it out, although Tuinity is a paper fork and should be the same...
> 
> If it would be the same, there would be no reason to use it.

actually yeah, Tuinity is optimized for servers that have a lot of player online...
