### ISSUE TITLE
1.8.0 forge crash

### ISSUE THREAD

**Issue by suchdifferent** [henkelmax/simple-voice-chat#433]
When i start Minecraft, i see this error in console.
Version - 1.8.0 forge both

`Exception in thread "VoiceChatClientThread"
[00:52:17] [VoiceChatClientThread/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.Error: 
There is an incompatible JNA native library installed on this system
Expected: 6.1.3
Found: 5.1.0
(at C:\Users\Name\AppData\Local\Temp\jna-2039745083\jna5529228681156938806.dll).
To resolve this issue you may do one of the following:
- remove or uninstall the offending library
- set the system property jna.nosys=true
- set jna.boot.library.path to include the path to the version of the 
jnidispatch library included with the JNA jar file you are using
[00:52:18] [VoiceChatClientThread/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: at com.sun.jna.Native.<clinit>(Native.java:230)
[00:52:18] [VoiceChatClientThread/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:87)
[00:52:18] [VoiceChatClientThread/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: at de.maxhenkel.voicechat.opus4j.Opus.<clinit>(Opus.java:16)
[00:52:18] [VoiceChatClientThread/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: at de.maxhenkel.voicechat.voice.common.OpusEncoder.<init>(OpusEncoder.java:22)
[00:52:18] [VoiceChatClientThread/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: at de.maxhenkel.voicechat.voice.client.MicThread.<init>(MicThread.java:26)
[00:52:18] [VoiceChatClientThread/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: at de.maxhenkel.voicechat.voice.client.Client.startMicThread(Client.java:100)
[00:52:18] [VoiceChatClientThread/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: at de.maxhenkel.voicechat.voice.client.Client.run(Client.java:132)
`
How can i fix it?

**Comment by henkelmax** [comment]
Please properly fill out the bug template.

**Comment by suchdifferent** [comment]
I fix it. I download new version and its work fine.
