### ISSUE TITLE
[Folia] Failed to initialize commodore command completion

### ISSUE THREAD

**Issue by FunixG** [henkelmax/simple-voice-chat#627]
Hello, I have a stacktrace when I start my minecraft server with the plugin installed in the plugin folder of my Folia server. The server is running with Folia 1.20.1 and Java OpenJDK 17 alpine. I do not have any plugins installed expected voicechat at the latest version.

Here is the stacktrace :

```java
[08:19:21 INFO]: [voicechat] Enabling voicechat v2.4.25
[08:19:21 INFO]: [voicechat] Initializing compatibility for Bukkit version 1.20.1-R0.1
[08:19:21 INFO]: [voicechat] Compatibility version 17
[08:19:21 WARN]: [voicechat] Failed to initialize commodore command completion
java.lang.IllegalStateException: Could not find any of the following classes: net.minecraft.commands.arguments.ArgumentEntity
        at de.maxhenkel.voicechat.compatibility.Compatibility.getClass(Compatibility.java:104) ~[voicechat.jar:?]
        at de.maxhenkel.voicechat.compatibility.Compatibility1_20.playerArgument(Compatibility1_20.java:36) ~[voicechat.jar:?]
        at de.maxhenkel.voicechat.integration.commodore.CommodoreCommands.playerArgument(CommodoreCommands.java:28) ~[voicechat.jar:?]
        at de.maxhenkel.voicechat.integration.commodore.CommodoreCommands.registerCompletions(CommodoreCommands.java:16) ~[voicechat.jar:?]
        at de.maxhenkel.voicechat.Voicechat.onEnable(Voicechat.java:90) ~[voicechat.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:646) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:557) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:462) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:345) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Thanks :D

**Comment by henkelmax** [comment]
Commodore does not work on all servers. The commodore command completion is optional for the plugin. You should be able to use it without any issues.

**Comment by henkelmax** [comment]
I just noticed from your stack trace that you are using the mojmapped server. This won't work with most plugins. This is for development purposes only.
