### ISSUE TITLE
maybe if player connect console huge spam and logs now have a more 2 gb

### ISSUE THREAD

**Issue by Medved0546** [henkelmax/simple-voice-chat#651]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
maybe if player connect console huge spam and logs now have a more 2 gb
and me and others player voicechat has a laggy voice if this happen
(or maybe its ddos?)

**Steps to reproduce the issue**
[23:39:53 WARN]:        at de.maxhenkel.voicechat.voice.server.Server$ProcessThread.run(Server.java:190)
[23:39:53 WARN]: java.net.SocketException: Operation not permitted
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.send0(Native Method)
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:901)
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:863)
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:821)
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.blockingSend(DatagramChannelImpl.java:853)
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramSocketAdaptor.send(DatagramSocketAdaptor.java:218)
[23:39:53 WARN]:        at java.base/java.net.DatagramSocket.send(DatagramSocket.java:664)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.plugins.impl.VoicechatSocketImpl.send(VoicechatSocketImpl.java:79)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.voice.server.ClientConnection.send(ClientConnection.java:37)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.voice.server.Server.sendPacket(Server.java:515)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.voice.server.Server.sendKeepAlives(Server.java:472)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.voice.server.Server.access$200(Server.java:34)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.voice.server.Server$ProcessThread.run(Server.java:190)
[23:39:53 WARN]: java.net.SocketException: Operation not permitted
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.send0(Native Method)
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:901)
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:863)
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:821)
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.blockingSend(DatagramChannelImpl.java:853)
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramSocketAdaptor.send(DatagramSocketAdaptor.java:218)
[23:39:53 WARN]:        at java.base/java.net.DatagramSocket.send(DatagramSocket.java:664)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.plugins.impl.VoicechatSocketImpl.send(VoicechatSocketImpl.java:79)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.voice.server.ClientConnection.send(ClientConnection.java:37)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.voice.server.Server.sendPacket(Server.java:515)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.voice.server.Server.sendKeepAlives(Server.java:472)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.voice.server.Server.access$200(Server.java:34)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.voice.server.Server$ProcessThread.run(Server.java:190)
[23:39:53 WARN]: java.net.SocketException: Operation not permitted
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.send0(Native Method)
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:901)
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:863)
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:821)
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.blockingSend(DatagramChannelImpl.java:853)
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramSocketAdaptor.send(DatagramSocketAdaptor.java:218)
[23:39:53 WARN]:        at java.base/java.net.DatagramSocket.send(DatagramSocket.java:664)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.plugins.impl.VoicechatSocketImpl.send(VoicechatSocketImpl.java:79)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.voice.server.ClientConnection.send(ClientConnection.java:37)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.voice.server.Server.sendPacket(Server.java:515)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.voice.server.Server.sendKeepAlives(Server.java:472)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.voice.server.Server.access$200(Server.java:34)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.voice.server.Server$ProcessThread.run(Server.java:190)
[23:39:53 WARN]: java.net.SocketException: Operation not permitted
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.send0(Native Method)
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:901)
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:863)
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:821)
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.blockingSend(DatagramChannelImpl.java:853)
[23:39:53 WARN]:        at java.base/sun.nio.ch.DatagramSocketAdaptor.send(DatagramSocketAdaptor.java:218)
[23:39:53 WARN]:        at java.base/java.net.DatagramSocket.send(DatagramSocket.java:664)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.plugins.impl.VoicechatSocketImpl.send(VoicechatSocketImpl.java:79)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.voice.server.ClientConnection.send(ClientConnection.java:37)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.voice.server.Server.sendPacket(Server.java:515)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.voice.server.Server.sendKeepAlives(Server.java:472)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.voice.server.Server.access$200(Server.java:34)
[23:39:53 WARN]:        at de.maxhenkel.voicechat.voice.server.Server$ProcessThread.run(Server.java:190)
[23:39:53 ERROR]: [voicechat] Dropping voice chat packets! Your Server might be overloaded!
[23:39:53 ERROR]: [voicechat] Packet queue has 624 packets

**Expected behavior**
fix this spam and catch this exception for maybe drop this spam packets idk

**Log files**
now its 2gb+ im lazy (error keeps recurring)
if you need this im uploading

**Versions**
- 1.16.5
- Paper
- 2.4.30

**Other mods**
im play with forgeoptifine 1.16.5 and only with this mod
plugins server -
[23:54:57 INFO]: Plugins (97): ACubelets, AdvancedEnchantments, ajLeaderboards, AntiDisconnectSpam, AntiRelog, AntiStringDupe, AquaticCrates, AureliumSkills, BAirDrop, BattlePass, BeacmcStaffWork, BottledExp, BountyHunters, BSpawner, ChatEx, ChatItem, Chunky, CleanroomGenerator, CMI, CMIEInjector*, CMILib, CommandTimer, ConsoleSpamFix, DailyRewards, DecentHolograms, DeluxeMenus, DungeonParties, EasyPayments, EnderPearlRestriction, ExecutableItems, FarmLimiter, fmDontInteractionAddon, HeadDatabase, IllegalStack, ItemEdit, ItemJoin, ItemsAdder, JumpOnline, JumpTeleports*, LagAssist, LastLoginAPI, LibsDisguises, LightAPI, LiteBans, LoneLibs, LootChest, LPX, LuckPerms, MagicCosmetics, MarriageMaster, MarryPlaceholderPlugin, Matrix, Minepacks, ModelEngine, MoneyFromMobs, Multiverse-Core, MyCommand, MythicDungeons, MythicMobs, MythicMobsGUI, NBTAPI, ODailyQuests, OreRegenerator, Parties, PCbank, PCGF_PluginLib, PhysicsControl, PlaceholderAPI, PlayerPoints, PlayerReport, PrimeAlchemist, ProtectionStones, ProtocolLib, PSAddon, RewardSystem, SCore, SecurityVillagers, SelectionVisualizer, ShopGUIPlus, spark, TAB, TntOptimizerPlugin, UltimateAutoRestart, UltimateCheatCheck, UltimateClans, Vault, ViaVersion, voicechat, VoidTeleportPlus, WheatPlugin, Winter, WorldEdit, WorldGuard, zAuctionHouseV3, zKoth, zMenu, ZNPCsPlus

**Screenshots (Optional)**
![WinSCP_zlwwtItGoG](https://github.com/henkelmax/simple-voice-chat/assets/140727790/5b3ceb93-1e48-45f8-89a7-4f659d46cbdd)

![putty_8OlXnfzg8J](https://github.com/henkelmax/simple-voice-chat/assets/140727790/2a9c4d9e-9faa-4808-9e97-6bbc4af78dcf)

**Comment by Medved0546** [comment]
and i have this in the velocity logs
[23:58:47 INFO]: [connected player] 2421 (/5.138.70.130:58928): kicked from server anarchy: You are sending too many packets, :(
[23:58:47 INFO]: [server connection] 2421 -> anarchy has disconnected
[23:58:47 INFO] [limboapi]: 2421 (/5.138.70.130:58928) has connected to the LimboHub Limbo
[23:58:47 INFO] [limboapi]: 2421 (/5.138.70.130:58928) has connected to the LimboHub Limbo
[23:58:56 WARN] [limboapi]: [connected player] 2421 (/5.138.70.130:58928) sent too big packet. (type: generic (PluginMessage packet (custom payload)), multi, length: 131097)
[23:58:56 INFO] [limboapi]: 2421 (/5.138.70.130:58928) has disconnected from the LimboHub Limbo
[00:00:32 INFO] [limboapi]: 2421 (/5.138.70.130:58967) has connected to the LimboHub Limbo
[00:00:38 WARN] [limboapi]: [connected player] 2421 (/5.138.70.130:58967) sent too big packet. (type: generic (PluginMessage packet (custom payload)), multi, length: 131160)
[00:00:38 INFO] [limboapi]: 2421 (/5.138.70.130:58967) has disconnected from the LimboHub Limbo
[00:01:03 INFO] [limboapi]: 2421 (/5.138.70.130:58975) has connected to the LimboHub Limbo
[00:01:08 WARN] [limboapi]: [connected player] 2421 (/5.138.70.130:58975) sent too big packet. (type: generic (PluginMessage packet (custom payload)), multi, length: 131160)
[00:01:08 INFO] [limboapi]: 2421 (/5.138.70.130:58975) has disconnected from the LimboHub Limbo
[00:01:37 INFO] [limboapi]: 2421 (/5.138.70.130:58981) has connected to the LimboHub Limbo
[00:01:42 WARN] [limboapi]: [connected player] 2421 (/5.138.70.130:58981) sent too big packet. (type: generic (PluginMessage packet (custom payload)), multi, length: 131160)
[00:01:42 INFO] [limboapi]: 2421 (/5.138.70.130:58981) has disconnected from the LimboHub Limbo
[00:02:14 INFO] [limboapi]: 2421 (/5.138.70.130:59020) has connected to the LimboHub Limbo
[00:02:22 WARN] [limboapi]: [connected player] 2421 (/5.138.70.130:59020) sent too big packet. (type: generic (PluginMessage packet (custom payload)), multi, length: 131160)
[00:02:22 INFO] [limboapi]: 2421 (/5.138.70.130:59020) has disconnected from the LimboHub Limbo
[00:05:03 INFO] [limboapi]: 2421 (/5.138.70.130:59050) has connected to the LimboHub Limbo
[00:05:17 WARN] [limboapi]: [connected player] 2421 (/5.138.70.130:59050) sent too big packet. (type: generic (PluginMessage packet (custom payload)), multi, length: 131160)
[00:05:17 INFO] [limboapi]: 2421 (/5.138.70.130:59050) has disconnected from the LimboHub Limbo
[00:05:44 INFO] [limboapi]: 2421 (/5.138.70.130:59079) has connected to the LimboHub Limbo
[00:05:49 WARN] [limboapi]: [connected player] 2421 (/5.138.70.130:59079) sent too big packet. (type: generic (PluginMessage packet (custom payload)), multi, length: 131160)
[00:05:49 INFO] [limboapi]: 2421 (/5.138.70.130:59079) has disconnected from the LimboHub Limbo
[00:10:12 INFO] [limboapi]: 2421 (/5.138.70.130:59173) has connected to the LimboHub Limbo
[00:10:17 WARN] [limboapi]: [connected player] 2421 (/5.138.70.130:59173) sent too big packet. (type: generic (PluginMessage packet (custom payload)), multi, length: 131160)
[00:10:17 INFO] [limboapi]: 2421 (/5.138.70.130:59173) has disconnected from the LimboHub Limbo
[00:11:00 INFO] [limboapi]: 2421 (/5.138.70.130:59189) has connected to the LimboHub Limbo
[00:11:05 WARN] [limboapi]: [connected player] 2421 (/5.138.70.130:59189) sent too big packet. (type: generic (PluginMessage packet (custom payload)), multi, length: 131160)
[00:11:05 INFO] [limboapi]: 2421 (/5.138.70.130:59189) has disconnected from the LimboHub Limbo
[00:13:28 INFO] [limboapi]: 2421 (/5.138.70.130:59235) has connected to the LimboHub Limbo
[00:13:33 WARN] [limboapi]: [connected player] 2421 (/5.138.70.130:59235) sent too big packet. (type: generic (PluginMessage packet (custom payload)), multi, length: 131160)
[00:13:33 INFO] [limboapi]: 2421 (/5.138.70.130:59235) has disconnected from the LimboHub Limbo
[00:13:58 INFO] [limboapi]: 2421 (/5.138.70.130:59275) has connected to the LimboHub Limbo
[00:14:10 WARN] [limboapi]: [connected player] 2421 (/5.138.70.130:59275) sent too big packet. (type: generic (PluginMessage packet (custom payload)), multi, length: 131160)
[00:14:10 INFO] [limboapi]: 2421 (/5.138.70.130:59275) has disconnected from the LimboHub Limbo
[00:14:35 INFO] [limboapi]: 2421 (/5.138.70.130:59317) has connected to the LimboHub Limbo
[00:14:40 WARN] [limboapi]: [connected player] 2421 (/5.138.70.130:59317) sent too big packet. (type: generic (PluginMessage packet (custom payload)), multi, length: 131160)
[00:14:40 INFO] [limboapi]: 2421 (/5.138.70.130:59317) has disconnected from the LimboHub Limbo
[00:19:42 INFO] [limboapi]: 2421 (/5.138.70.130:59371) has connected to the LimboHub Limbo
[00:19:47 WARN] [limboapi]: [connected player] 2421 (/5.138.70.130:59371) sent too big packet. (type: generic (PluginMessage packet (custom payload)), multi, length: 131160)
[00:19:47 INFO] [limboapi]: 2421 (/5.138.70.130:59371) has disconnected from the LimboHub Limbo
[00:20:37 INFO] [limboapi]: 2421 (/5.138.70.130:59412) has connected to the LimboHub Limbo
[00:20:41 WARN] [limboapi]: [connected player] 2421 (/5.138.70.130:59412) sent too big packet. (type: generic (PluginMessage packet (custom payload)), multi, length: 131160)
[00:20:41 INFO] [limboapi]: 2421 (/5.138.70.130:59412) has disconnected from the LimboHub Limbo

**Comment by Medved0546** [comment]
now i contact with this player an he give me a logs
[latest.zip](https://github.com/henkelmax/simple-voice-chat/files/13762666/latest.zip)

**Comment by henkelmax** [comment]
This is not a bug. Please visit the discord if you need help.
