### ISSUE TITLE
SVC on Server Became not Working After a Weird Lag

### ISSUE THREAD

**Issue by Shiroiame-Kusu** [henkelmax/simple-voice-chat#665]
### Confirmation

- [X] I have read the wiki

### Bug description

Everyone in my server was chatting happily at first.
but then, the server seemed stuck, and after the lag, SVC become not responding at all.
Here is the log.
```
[17:16:59] [Netty Server IO #6/ERROR]: Packet encoding of packet ID 100 threw (skippable? true)
io.netty.handler.codec.EncoderException: String too big (was 343941 characters, max 262144)
	at net.minecraft.network.FriendlyByteBuf.writeUtf(FriendlyByteBuf.java:754) ~[?:?]
	at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.write(ClientboundSystemChatPacket.java:48) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:41) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[paper-1.20.1.jar:git-Paper-196]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at me.arasple.mc.trmenu.taboolib.module.nms.ChannelHandler.write(ChannelHandler.kt:22) ~[TrMenu-3.2.0b.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at me.matsubara.listenmode.util.GlowingEntities$Packets$2.write(GlowingEntities.java:737) ~[ListenMode-2.2.3.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib (2).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib (2).jar:?]
	at net.minecraft.network.Connection.doSendPacket(Connection.java:476) ~[?:?]
	at net.minecraft.network.Connection.lambda$sendPacket$11(Connection.java:450) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib (2).jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
And I tried to use plugman to reload this plugin, SVC reload successfully but still not working.
```
[17:18:19] [Server thread/INFO]: Shiroame_Kusu issued server command: /plugman reload voicechat
[17:18:19] [Server thread/INFO]: [voicechat] Disabling voicechat v2.4.30
[17:18:20] [Server thread/INFO]: [voicechat] Loading server plugin voicechat v2.4.30
[17:18:20] [Server thread/INFO]: [voicechat] Enabling voicechat v2.4.30
[17:18:20] [Server thread/INFO]: [voicechat] Initializing compatibility for Bukkit version 1.20.1-R0.1
[17:18:20] [Server thread/INFO]: [voicechat] Compatibility version 17
[17:18:20] [Server thread/INFO]: [voicechat] Successfully initialized commodore command completion
[17:18:20] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: voicechat [2.4.30]
[17:18:20] [Server thread/INFO]: [voicechat] Successfully registered PlaceholderAPI expansion
[17:18:20] [Server thread/ERROR]: [voicechat] Simple Voice Chat does not support reloads! Expect that things will break!
[17:18:20] [Server thread/INFO]: [voicechat] Loading plugins
[17:18:20] [Server thread/INFO]: [voicechat] Loaded 0 plugin(s)
[17:18:20] [Server thread/INFO]: [voicechat] Initializing plugins
[17:18:20] [Server thread/INFO]: [voicechat] Initialized 0 plugin(s)
[17:18:20] [Server thread/WARN]: [voicechat] Running in offline mode - Voice chat encryption is not secure!
[17:18:20] [VoiceChatServerThread/INFO]: [voicechat] Voice host is 'xxx'
[17:18:20] [VoiceChatServerThread/INFO]: [voicechat] Voice chat server started at port 24455
```

### Minecraft version

1.20.1

### Mod/Plugin version

1.20.1-2.4.30

### Mod/Plugin loader and version

Paper 1.20.1

### Steps to reproduce

In fact, I didn't know how to reproduce this issue, sorry about this.

### Log files

None, because almost all the error are the same, as I provided above.

**Comment by henkelmax** [comment]
1. Please provide the full logs like stated in the template.
2. Please update the plugin to the latest version.
3. Most plugins break if you reload them. Reloading is not supported, see your logs:
> [17:18:20] [Server thread/ERROR]: [voicechat] Simple Voice Chat does not support reloads! Expect that things will break!
4. If this issue is not reproducible I can't help you. Please come back if you know how to reproduce it.
5. We don't provide support for offline mode servers
