### ISSUE TITLE
Server crashes when a player joins

### ISSUE THREAD

**Issue by xijdk** [henkelmax/simple-voice-chat#759]
### Confirmation

- [X] I have read the wiki

### Bug description

My Fabric server crashes when a player joins. Crash is occurring when Voice chat requests Fabric permissions API:
```[20:27:30] [Server thread/INFO]: [voicechat] Using Fabric Permissions API
[20:27:30] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'net.minecraft.class_2168 net.minecraft.class_3222.method_64396()'
	at knot/me.lucko.fabric.api.permissions.v0.Util.commandSourceFromEntity(Util.java:38) ~[fabric-permissions-api-v0-0.3.3-82369eda3a4fc310.jar:?]
	at knot/me.lucko.fabric.api.permissions.v0.Permissions.check(Permissions.java:160) ~[fabric-permissions-api-v0-0.3.3-82369eda3a4fc310.jar:?]
	at knot/de.maxhenkel.voicechat.permission.FabricPermissionManager$1.hasPermission(FabricPermissionManager.java:16) ~[voicechat-fabric-1.21.1-2.5.26.jar:?]
	at knot/de.maxhenkel.voicechat.command.VoicechatCommands.checkPermission(VoicechatCommands.java:293) ~[voicechat-fabric-1.21.1-2.5.26.jar:?]
	at knot/de.maxhenkel.voicechat.command.VoicechatCommands.lambda$register$2(VoicechatCommands.java:45) ~[voicechat-fabric-1.21.1-2.5.26.jar:?]
	at knot/com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:65) ~[brigadier-1.3.10.jar:?]
	at knot/net.minecraft.class_2170.method_9239(class_2170.java:398) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2170.method_9239(class_2170.java:421) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2170.method_9241(class_2170.java:392) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3324.method_14596(class_3324.java:645) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3324.method_14576(class_3324.java:546) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3324.method_14570(class_3324.java:206) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_8610.method_52408(class_8610.java:152) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_8736.method_53043(class_8736.java:22) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_8736.method_11054(class_8736.java:8) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_2600.method_11072(class_2600.java:27) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18857(class_1255.java:145) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]```
	
Other mods installed: Audaki Cart Engine, C2ME, Chunky, Cloth Config, Fabric API, Fabric Language Kotlin, Ferritecore, FSit, Lithium, modern fix, NoChatReports, Noisium, Spark, Threadtweak. Without Simple Voice Chat, this issue doesn't arise

I can see that it tries to use methods from Fabric Permissions API — I don't have this mod installed; and it doesn't tell it's needed anywhere in the docs. 

### Minecraft version

1.21.1

### Mod/Plugin version

1.21.1-2.5.26

### Mod/Plugin loader and version

Fabric Loader 0.16.9

### Steps to reproduce

1. Start a fabric server with simple voice chat
2. Join it

### Expected behavior

No crashes on server join

### Log files

https://gist.github.com/xijdk/05e5edd0be28d80d34e62338517014a4

### Screenshots

_No response_

**Comment by henkelmax** [comment]
This is caused by a mod shipping with an incompatible, outdated version of the fabric permissions API. This is not an issue with SVC.
