### ISSUE TITLE
Spamming console for every connected player

### ISSUE THREAD

**Issue by linx80** [henkelmax/simple-voice-chat#80]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
Spams error message in console on hosted server. Keeps reconnecting players. Happened today when server was moved from a local server to hosted server at Bisect. Port is change to a port thats opened at host site.

**Steps to reproduce the issue**
No

**Expected behavior**
It shouldn't spam console.

**Log files**
[04.03 12:33:31] [Server] [VoiceChatPacketProcessingThread/INFO] [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:192]: 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
[04.03 12:33:31] [Server] [VoiceChatPacketProcessingThread/INFO] [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:192]: 	at java.util.HashMap$ValueIterator.next(HashMap.java:1474)
[04.03 12:33:31] [Server] [VoiceChatPacketProcessingThread/INFO] [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:192]: 	at de.maxhenkel.voicechat.voice.server.Server.keepAlive(Server.java:205)
[04.03 12:33:31] [Server] [VoiceChatPacketProcessingThread/INFO] [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:192]: 	at de.maxhenkel.voicechat.voice.server.Server.access$100(Server.java:18)
[04.03 12:33:31] [Server] [VoiceChatPacketProcessingThread/INFO] [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:192]: 	at de.maxhenkel.voicechat.voice.server.Server$ProcessThread.run(Server.java:113)

**Versions**
- Minecraft version 1.16.5
- Forge version 36.0.45
- Mod version latest

**Other mods**
ALOT of mods. Running modpack NTI Modded.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Please send me the full logs with something like GitHub Gist

**Comment by abernardi597** [comment]
Seems like a duplicate of #76

**Comment by linx80** [comment]
Yes, what abernardi597 wrote. Same issue.

**Comment by henkelmax** [comment]
I think so... But that should be fixed in the latest version...

**Comment by henkelmax** [comment]
> Yes, what abernardi597 wrote. Same issue.

So you are not using the latest version?

**Comment by linx80** [comment]
> I think so... But that should be fixed in the latest version...

**Comment by henkelmax** [comment]
Next time, please note the exact version you are using.

**Comment by linx80** [comment]
> Next time, please note the exact version you are using.

Yes, sorry.

**Comment by linx80** [comment]
Updating the mod through CurseForge app installs the Fabric version which means I can not include it in my modpack without CurseForge complains about it.
