### ISSUE TITLE
Netcat Port Test Works, But I am still getting "Voice chat unavailable" message

### ISSUE THREAD

**Issue by JurassikLizard** [henkelmax/simple-voice-chat#92]
I setup the server I was supposed to, I added the mod to the server and I added the fabric API. I also have 3 more mods, Lithium, Posphor and Carboard (Bukkit4Fabric). On my client I have the voice chat mod, fabric API, and OptiFabric and OptiFine.

I setup netcat like it says on the wiki page. And the connection worked, I am using port 25570.

First picture is client, second one is server, I accidentally typed hey in the server window.

![image](https://user-images.githubusercontent.com/51036391/110491123-f6577380-80be-11eb-8fd0-bfec1c150db8.png)

![image](https://user-images.githubusercontent.com/51036391/110491165-ff484500-80be-11eb-8b6d-fa703c848090.png)

**Comment by henkelmax** [comment]
Does it work both ways?
Are you using a server with multiple network adapters?
Have you tried it without any other mods?
Please send me your log files.
Which mod version and which Fabric version are you using?

**Comment by JurassikLizard** [comment]
Server Config:
#
#Tue Mar 09 15:07:22 UTC 2021
voice_fade_distance=90.0
sample_rate=16000
port=25570
mtu_size=900
voice_distance=110.0
keep_alive=1000
bind_address=

Client Config:
#
#Tue Mar 09 09:05:22 EST 2021
output_buffer_size=6
voice_activation_threshold=-60.036363636363646
speaker=Headset Earphone (Plantronics Blackwire 7225 Series)
microphone=Headset Microphone (Plantronics Blackwire 7225 Series)
microphone_amplification=4.0
microphone_activation_type=PTT
voice_chat_volume=1.0

**Comment by henkelmax** [comment]
> And, if it helps, it says that my client constantly times out it game
> ![image](https://user-images.githubusercontent.com/51036391/110491908-b349d000-80bf-11eb-870d-52db0af22fd9.png)

It looks like it is the bind IP issue.

**Comment by JurassikLizard** [comment]
[FABRIC][1.16.5] Simple Voice Chat 1.16.5-1.0.9

^^ The version I used

**Comment by JurassikLizard** [comment]
> > And, if it helps, it says that my client constantly times out it game
> > ![image](https://user-images.githubusercontent.com/51036391/110491908-b349d000-80bf-11eb-870d-52db0af22fd9.png)
> 
> It looks like it is the bind IP issue.

How would I fix this

**Comment by henkelmax** [comment]
Just add your servers IP address to this config entry: `bind_address=`

**Comment by JurassikLizard** [comment]
Ok, I will try that

**Comment by JurassikLizard** [comment]
```
[15:17:31] [VoiceChatServerThread/ERROR]: Failed to bind to address '35.186.176.248'
[15:17:31] [VoiceChatServerThread/INFO]: [STDERR]: java.net.BindException: Cannot assign requested address (Bind failed)
[15:17:31] [VoiceChatServerThread/INFO]: [STDERR]:      at java.base/java.net.PlainDatagramSocketImpl.bind0(Native Method)
[15:17:31] [VoiceChatServerThread/INFO]: [STDERR]:      at java.base/java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:131)
[15:17:31] [VoiceChatServerThread/INFO]: [STDERR]:      at java.base/java.net.DatagramSocket.bind(DatagramSocket.java:394)
[15:17:31] [VoiceChatServerThread/INFO]: [STDERR]:      at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:244)
[15:17:31] [VoiceChatServerThread/INFO]: [STDERR]:      at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:301)
[15:17:31] [VoiceChatServerThread/INFO]: [STDERR]:      at de.maxhenkel.voicechat.voice.server.Server.run(Server.java:60)
```
Is what happens when I do the bind-address

**Comment by JurassikLizard** [comment]
```
[15:17:31] [Server thread/INFO]: Done (12.626s)! For help, type "help"
[15:17:31] [VoiceChatServerThread/ERROR]: Failed to bind to address '35.186.176.248'
[15:17:31] [VoiceChatServerThread/INFO]: [STDERR]: java.net.BindException: Cannot assign requested address (Bind failed)
[15:17:31] [VoiceChatServerThread/INFO]: [STDERR]:      at java.base/java.net.PlainDatagramSocketImpl.bind0(Native Method)
[15:17:31] [VoiceChatServerThread/INFO]: [STDERR]:      at java.base/java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:131)
[15:17:31] [VoiceChatServerThread/INFO]: [STDERR]:      at java.base/java.net.DatagramSocket.bind(DatagramSocket.java:394)
[15:17:31] [VoiceChatServerThread/INFO]: [STDERR]:      at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:244)
[15:17:31] [VoiceChatServerThread/INFO]: [STDERR]:      at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:301)
[15:17:31] [VoiceChatServerThread/INFO]: [STDERR]:      at de.maxhenkel.voicechat.voice.server.Server.run(Server.java:60)
2021-03-09 15:17:31,517 Server thread WARN JNDI lookup class is not available because this JRE does not support JNDI. JNDI string lookups will not be available, continuing configuration. Ignoring java.lang.ClassCastException: Cannot cast org.apache.logging.log4j.core.lookup.JndiLookup to org.apache.logging.log4j.core.lookup.StrLookup
2021-03-09 15:17:31,519 Server thread WARN JMX runtime input lookup class is not available because this JRE does not support JMX. JMX lookups will not be available, continuing configuration. Ignoring java.lang.ClassCastException: Cannot cast org.apache.logging.log4j.core.lookup.JmxRuntimeInputArgumentsLookup to org.apache.logging.log4j.core.lookup.StrLookup
2021-03-09 15:17:31,522 Server thread WARN JNDI lookup class is not available because this JRE does not support JNDI. JNDI string lookups will not be available, continuing configuration. Ignoring java.lang.ClassCastException: Cannot cast org.apache.logging.log4j.core.lookup.JndiLookup to org.apache.logging.log4j.core.lookup.StrLookup
2021-03-09 15:17:31,523 Server thread WARN JMX runtime input lookup class is not available because this JRE does not support JMX. JMX lookups will not be available, continuing configuration. Ignoring java.lang.ClassCastException: Cannot cast org.apache.logging.log4j.core.lookup.JmxRuntimeInputArgumentsLookup to org.apache.logging.log4j.core.lookup.StrLookup
2021-03-09 15:17:31,567 Server thread WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
```

**Comment by henkelmax** [comment]
> [FABRIC][1.16.5] Simple Voice Chat 1.16.5-1.0.9
> 
> ^^ The version I used

This is not the latest version. Please update to the latest version.

**Comment by henkelmax** [comment]
> ```
> [15:17:31] [Server thread/INFO]: Done (12.626s)! For help, type "help"
> [15:17:31] [VoiceChatServerThread/ERROR]: Failed to bind to address '35.186.176.248'
> [15:17:31] [VoiceChatServerThread/INFO]: [STDERR]: java.net.BindException: Cannot assign requested address (Bind failed)
> [15:17:31] [VoiceChatServerThread/INFO]: [STDERR]:      at java.base/java.net.PlainDatagramSocketImpl.bind0(Native Method)
> [15:17:31] [VoiceChatServerThread/INFO]: [STDERR]:      at java.base/java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:131)
> [15:17:31] [VoiceChatServerThread/INFO]: [STDERR]:      at java.base/java.net.DatagramSocket.bind(DatagramSocket.java:394)
> [15:17:31] [VoiceChatServerThread/INFO]: [STDERR]:      at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:244)
> [15:17:31] [VoiceChatServerThread/INFO]: [STDERR]:      at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:301)
> [15:17:31] [VoiceChatServerThread/INFO]: [STDERR]:      at de.maxhenkel.voicechat.voice.server.Server.run(Server.java:60)
> 2021-03-09 15:17:31,517 Server thread WARN JNDI lookup class is not available because this JRE does not support JNDI. JNDI string lookups will not be available, continuing configuration. Ignoring java.lang.ClassCastException: Cannot cast org.apache.logging.log4j.core.lookup.JndiLookup to org.apache.logging.log4j.core.lookup.StrLookup
> 2021-03-09 15:17:31,519 Server thread WARN JMX runtime input lookup class is not available because this JRE does not support JMX. JMX lookups will not be available, continuing configuration. Ignoring java.lang.ClassCastException: Cannot cast org.apache.logging.log4j.core.lookup.JmxRuntimeInputArgumentsLookup to org.apache.logging.log4j.core.lookup.StrLookup
> 2021-03-09 15:17:31,522 Server thread WARN JNDI lookup class is not available because this JRE does not support JNDI. JNDI string lookups will not be available, continuing configuration. Ignoring java.lang.ClassCastException: Cannot cast org.apache.logging.log4j.core.lookup.JndiLookup to org.apache.logging.log4j.core.lookup.StrLookup
> 2021-03-09 15:17:31,523 Server thread WARN JMX runtime input lookup class is not available because this JRE does not support JMX. JMX lookups will not be available, continuing configuration. Ignoring java.lang.ClassCastException: Cannot cast org.apache.logging.log4j.core.lookup.JmxRuntimeInputArgumentsLookup to org.apache.logging.log4j.core.lookup.StrLookup
> 2021-03-09 15:17:31,567 Server thread WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
> ```

Which hoster are you using?

**Comment by JurassikLizard** [comment]
Google Cloud Platform, so a Private VM, and, where would I find the latest version, I see this on the curse page:
![image](https://user-images.githubusercontent.com/51036391/110493976-21db5d80-80c1-11eb-93de-3cbfa819de2e.png)

**Comment by JurassikLizard** [comment]
This isn't a standard minecraft host, it's a private vm that is being used to host minecraft, it's not a designated minecraft hoster, it's cloud virtual machines. and that is my bind address, it is what I use to connect to my server.

**Comment by henkelmax** [comment]
I know that. But there might be something special you need to do, to bind the address.

Quote from the FAQ:

>  I am not tech support. Ask your server hoster or use the internet to search for a solution.

The issue section is only for bugs and feature requests. I can't help everyone with their problems. I have not enough time to help everybody. You have to find that out by yourself.

**Comment by JurassikLizard** [comment]
It seems to have fixed it self, oh well

**Comment by JurassikLizard** [comment]
Ok, I fixed it, for anyone wondering how I did it, I set the bind address to 0.0.0.0
